issue #218. revert newer httpclient version because of non-deterministic test failures.
recent commit caused non-deterministic failures in UserIntegrationTest tests:
> IllegalStateException: Connection pool shut down

until we can be sure that the new HttpClient works fine, we should keep the old
tested code in "master".